---
charset:
  standard:
    numbers: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
    lower_case: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
    upper_case: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
    special: ["+", "@", "\"", "*", "#", "%", "&", "/", "|", "(", ")", "=", "?", "'", "^", "~", "`", "[", "]", "!", "{", "}", "$", "-", "_", ".", ":", ",", ";", "<", ">"]
  extended:
    lower_case: ["ä", "ö", "ü", "è", "à", "é"]
    upper_case: ["Ä", "Ö", "Ü", "È", "À", "É"]
    special: ["€", "¬", "¨", "£", "ç", "°", "§", "\\"]
